services:
  db:
    image: postgres:13-alpine
    container_name: db-container
    ports:
      - "5432:5432"
    user: postgres
    environment:
      TZ: "Asia/Tokyo"
      LANG: ja_JP.utf8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    container_name: app-container
    build:
      target: dev
    command: >
      /bin/sh -c "rm -f tmp/pids/server.pid &&
      bin/rails db:migrate &&
      bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
