default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('DB_HOST') { 'db-container' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  database: <%= ENV.fetch('DB_NAME') { 'dev-db' } %>

development:
  <<: *default

test:
  <<: *default
  database: test-db

# [START cloudrun_rails_database]
production:
  <<: *default
# [END cloudrun_rails_database]

